interface Patient {
  id: string;
  idCC: string;
  firstName: string;
  lastName: string;
  address: string;
  locality: string;
  country: string;
  postalCode: string;
  documentNumber: string;
  documentType: string;
  phoneNumber: string;
  image: string;
  age: number;
  employment: string;
  dischargeDate: Date;
  socialWork: string;
  socialWorkNumber: string;
  consent: boolean;
  status: string;
  statusMonitoring: string;
  attendedUserId: string;
  mainMail: string;
  secondaryMail: string;
  generalInformation: string;
  smoker: string;
  smokerDetails: string;
  weight: string;
  diet: string;
  dietDetails: string;
  cognitiveImpairment: string;
  cognitiveImpairmentDetails: string;
  fluidRestriction: string;
  mobilityProblems: string;
  communicationProblems: string;
  conditions: any;
  allergies: any;
  medication: any;
  medicationAdjustment: any;
  rescueMedicine: any;
  hospitalIncome: any;
  contactsOutsideOfficeHours: any;
  createdAt: Date;
  updatedAt: Date;
}

export default Patient;
